
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6379:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
#   redis:
#     env_file: .env
#     image: redis:latest
#     container_name: redis_container
#     ports:
#       - '6379:6379'
#     networks:
#       - redis
# networks:
#   postgres:
#     driver: bridge
#   redis:
#     driver: bridge
